project:
  type: website
  output-dir: _site

execute:
  eval: false

website:
  title: "Seminars — Fintech DL HSE"
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: "Обзор"
      - section: "Семинары"
        contents:
          - 01_seminar_mlp_autograd/01_seminar_mlp_autograd.ipynb
          - 02_activations_initialization_dataloader_trainer/02_activations_initialization_dataloader_trainer.ipynb
          - 03_optimization_regularization/03_seminar_optimization_regularization.ipynb
          - 04_cnn/04_seminar_cnn.ipynb
          - 05_cv/05_seminar_cv.ipynb
          - 06_gan/06_gan.ipynb
          - 07_vae_diffusion/07_vae_diffusion.ipynb
          - 08_nlp_w2v/08_nlp_w2v.ipynb
          - 09_rnn_transformer/08_seminar_rnn_transformer.ipynb
          - 10_llm/10_llm.ipynb
